import type { Config } from "tailwindcss";

export default {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#006172",
        "on-primary": "#ffffff",
        "primary-container": "#2a7a8c",
        "on-primary-container": "#e6f9ff",
        "primary-fixed": "#acedff",
        "primary-fixed-dim": "#88d1e5",
        "on-primary-fixed": "#001f26",
        "on-primary-fixed-variant": "#004e5c",
        "inverse-primary": "#88d1e5",
        secondary: "#276676",
        "on-secondary": "#ffffff",
        "secondary-container": "#b0ecfe",
        "on-secondary-container": "#2e6c7c",
        "secondary-fixed": "#b0ecfe",
        "secondary-fixed-dim": "#94d0e1",
        "on-secondary-fixed": "#001f26",
        "on-secondary-fixed-variant": "#004e5d",
        tertiary: "#4b5b5b",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#637473",
        "on-tertiary-container": "#e8faf9",
        "tertiary-fixed": "#d4e6e5",
        "tertiary-fixed-dim": "#b8cac9",
        "on-tertiary-fixed": "#0e1e1e",
        "on-tertiary-fixed-variant": "#3a4a49",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#edfcff",
        "on-background": "#0d1e21",
        surface: "#edfcff",
        "on-surface": "#0d1e21",
        "on-surface-variant": "#3f484b",
        "surface-dim": "#cbdde1",
        "surface-bright": "#edfcff",
        "surface-variant": "#d3e6ea",
        "surface-tint": "#0a6879",
        "surface-container": "#def1f5",
        "surface-container-low": "#e4f7fb",
        "surface-container-high": "#d9ecef",
        "surface-container-highest": "#d3e6ea",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#223336",
        "inverse-on-surface": "#e1f4f8",
        outline: "#6f797c",
        "outline-variant": "#bec8cb",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1200px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
        gutter: "32px",
        "section-padding": "120px",
        unit: "8px",
      },
      fontFamily: {
        sans: ["var(--font-manrope)", "Manrope", "system-ui", "sans-serif"],
        manrope: [
          "var(--font-manrope)",
          "Manrope",
          "system-ui",
          "sans-serif",
        ],
      },
      fontSize: {
        "chat-bubble": ["15px", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-bold": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "700" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      boxShadow: {
        ambient: "0 40px 80px -20px rgba(42, 122, 140, 0.04)",
        glass: "0 8px 32px 0 rgba(42, 122, 140, 0.04)",
        "glass-lg": "0 24px 60px -12px rgba(42, 122, 140, 0.18)",
        "glow-teal": "0 0 30px rgba(42, 122, 140, 0.35)",
      },
      animation: {
        "pulse-breath": "pulse-breath 8s ease-in-out infinite",
        "pulse-teal": "pulse-teal 2s infinite",
        "pulse-error": "pulse-error 2s infinite",
        "gradient-shift": "gradient-shift 12s ease-in-out infinite",
        "gradient-mesh": "gradient-mesh 30s ease-in-out infinite",
        float: "float 6s ease-in-out infinite",
        shimmer: "shimmer 2.5s linear infinite",
      },
      keyframes: {
        "pulse-breath": {
          "0%, 100%": { transform: "scale(1)", opacity: "0.3" },
          "50%": { transform: "scale(1.5)", opacity: "0.15" },
        },
        "pulse-teal": {
          "0%": {
            transform: "scale(0.95)",
            boxShadow: "0 0 0 0 rgba(42, 122, 140, 0.7)",
          },
          "70%": {
            transform: "scale(1)",
            boxShadow: "0 0 0 10px rgba(42, 122, 140, 0)",
          },
          "100%": {
            transform: "scale(0.95)",
            boxShadow: "0 0 0 0 rgba(42, 122, 140, 0)",
          },
        },
        "pulse-error": {
          "0%": {
            transform: "scale(0.95)",
            boxShadow: "0 0 0 0 rgba(186, 26, 26, 0.7)",
          },
          "70%": {
            transform: "scale(1)",
            boxShadow: "0 0 0 10px rgba(186, 26, 26, 0)",
          },
          "100%": {
            transform: "scale(0.95)",
            boxShadow: "0 0 0 0 rgba(186, 26, 26, 0)",
          },
        },
        "gradient-shift": {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
        "gradient-mesh": {
          "0%, 100%": { transform: "translate(0, 0) scale(1)" },
          "33%": { transform: "translate(8%, -6%) scale(1.08)" },
          "66%": { transform: "translate(-6%, 8%) scale(0.95)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-12px)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
    },
  },
  plugins: [],
} satisfies Config;
